export const technologies = [
  { name: "Docker", icon: "/technologies/docker-logo.svg" },
  { name: "OpenStack", icon: "/technologies/open-stack-logo.svg" },
  { name: "Kubernetes", icon: "/technologies/kubernetes-logo.svg" },
  { name: "Ansible", icon: "/technologies/ansible-logo.svg" },
  { name: "Terraform", icon: "/technologies/terraform-logo.svg" },
  { name: "AWS", icon: "/technologies/aws-logo.svg" },
  { name: "Google Cloud", icon: "/technologies/google-cloud-logo.svg" },
  { name: "ArgoCD", icon: "/technologies/argo-logo.svg" },
  { name: "Jenkins", icon: "/technologies/jenkins-logo.svg" },
  { name: "GitLab CI", icon: "/technologies/gitlab-logo.svg" },
  { name: "Java", icon: "/technologies/java-logo.svg" },
  { name: "Node.js", icon: "/technologies/node-js-logo.svg" },
  { name: "Spring", icon: "/technologies/spring-boot-logo.svg" },
  { name: "HTML5", icon: "/technologies/html5-logo.svg" },
  { name: "CSS3", icon: "/technologies/css3-logo.svg" },
  { name: "React.JS", icon: "/technologies/react-logo.svg" },
  { name: "JavaScript", icon: "/technologies/javascript-logo.svg" },
  { name: "Figma", icon: "/technologies/figma-logo.svg" },
];
